export const TEL = {
  clinic: 'దంత క్లినిక్',
  invoice: 'ఇన్వాయిస్',
  patient: 'రోగి',
  date: 'తేదీ',
  description: 'వివరం',
  hsn: 'HSN',
  gst: 'GST',
  taxable: 'పన్ను విలువ',
  amount: 'మొత్తం',
  subtotal: 'మొత్తం',
  cgst: 'CGST',
  sgst: 'SGST',
  igst: 'IGST',
  roundOff: 'రౌండ్ ఆఫ్',
  total: 'మొత్తం చెల్లించాల్సిన మొత్తం',
  payment: 'చెల్లింపు',
  status: 'స్థితి',
  paid: 'చెల్లించబడింది',
  pending: 'పెండింగ్',
  cancelled: 'రద్దు చేయబడింది',
  thankYou: 'ధన్యవాదాలు · మళ్లీ వస్తారామని ఆహ్వానిస్తున్నాము',
  gstin: 'GSTIN',
  registration: 'రిజిస్ట్రేషన్',
  phone: 'ఫోన్',
  thisIsA: 'ఇది కంప్యూటర్ ద్వారా తయారు చేసిన రసీదు',
  exempt: 'పన్ను మినహాయింపు',
};

export function t(key) { return TEL[key] || key; }
